#Build Settings
destination: public
source: src
exclude: ['node_modules']

# Site settings
title: Music Centre London
description: > # this means to ignore newlines until "baseurl:"
  Music Centre London is a registered charity with the objective of promoting, maintaining, improving and advancing education by the provision of musical tuition, both choral and instrumental, to children and young persons of and under the age of twenty one across Islington and Southwark.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://musiccentrelondon.com" # the base hostname & protocol for your site

#social
facebook: musiccentrelondon
alumin: groups/musiccentrelondonalumni
twitter-creator: mcclowes
twitter-username: codogoio

permalink: pretty
locale: "en-GB"

# Build settings
markdown: kramdown

# Tracker
ga-analytics: UA-99016378-1